language: python
cache: pip

matrix:
    include:
        - python: 2.7
          env: TOX_ENV=py27
        - python: 3.6
          env: TOX_ENV=py36,coverage

install:
    - pip install -r requirements.txt

before_script:
    - flake8 . --max-line-length=127 --show-source --statistics
    - pylint --rcfile=.pylintrc  algorithms

script:
    - tox -e $TOX_ENV
